"""empty message

Revision ID: e98ac330d725
Revises: 
Create Date: 2025-10-01 08:58:17.285635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98ac330d725'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tb_valvula',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_valvula', sa.String(length=120), nullable=False),
    sa.Column('local_valvula', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_registro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('data_acionamento', sa.DateTime(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_valvula', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['tb_usuario.id'], ),
    sa.ForeignKeyConstraint(['id_valvula'], ['tb_valvula.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_registro')
    op.drop_table('tb_valvula')
    op.drop_table('tb_usuario')
    # ### end Alembic commands ###
